version: '3'

services:
  api:
    container_name: todo-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .envfile
    volumes:
      - .:/app/
    depends_on:
      - db

  db:
    container_name: todo-db
    image: postgres:13-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: todo
